config/routes.rb
Rails.application.routes.draw do
  get 'creator/index'

  get 'index/index'
  root 'index#index'
  get 'counselor/show'

  get 'counselor/new'

  get 'game/create'

  get 'iqtest/show'

  get 'el/index'

  get 'eligibilty/new'

  get 'home/index'

  post 'el/index'
  post 'home/new'
  get 'home/edit'
  get 'counselor/index'
  get 'counselor/show'
  post 'counselor/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/msg.rb
class Msg < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/counselor_controller.rb
class CounselorController < ApplicationController
  layout 'counselor'
  def show
    @msg= Msg.new
  end
  def index
    end
  def new
    @msg1=Msg.create(msg_params)
    if @msg1.save
      redirect_to  counselor_index_path
    end
  end
  private
  def msg_params
    params.require(:msg).permit(:name, :email_id, :query )
  end
end

app/controllers/creator_controller.rb
class CreatorController < ApplicationController
  def index
  end
end

app/controllers/el_controller.rb
class ElController < ApplicationController
  layout 'eligibilty'
  def index
    @name=params[:fname]
    @mark=params[:lname]

    college( @name,@mark)
    end

      def college( name,m)
       if name == "Manipal"
          manipal(m)
        elsif name == "Mains"
          mains(m)
       elsif name == "SRM"
         srm(m)
       else
         @submit = "Sorry! No results found.
                    Please try again."
       end
      end
      def manipal(m)
        m=m.to_i
        if m >= 1 && m <= 100
          @submit= "You will get all branches in muj other than cs.Thank You, All the best for your future"

        elsif
        m > 100 && m<=150
          @submit= "All branches in muj,lower branches in Main campus, all in SIkkim"
          #puts  "Thank You, All the best for your future"
        elsif
        m > 150 && m <=200
          @submit = "All branches in muj,all branches in Main campus except CS,Mech, all in SIkkim "
          #puts "Thank You, All the best for your future"
        else
          @submit = "All branches in all campuses. Contratulations!"
          # "Thank You, All the best for your future"
        end
      end
def mains(m)
  m=m.to_i
    if m>=0 && m <=100
    @submit = "You wont get any NIT or IIT. Please look for other colleges. All the Best"
    elsif
       m>100 && m<=150
        @submit = "Congratulations! You hvae qualified for JEE Advanced.You will get newer NITs like IIT Ranchi,NIT Srinagar and other good colleges like K.J Somaiya, Thapar. All the Best"
      elsif
         m>150 && m<= 200
      @submit = "Congratulations! You hvae qualified for JEE Advanced.You will get newer IITS good NITs like NIT Raipur,NIT Srinagar and other good colleges like K.J Somaiya, Thapar. All the Best"
    elsif
      m>200 && m<=300
      @submit = "Congratulations! You hvae qualified for JEE Advanced.You will get good NITs NIT Suratkal,NIT Jaipur,NIT Srinagar and other good colleges like K.J Somaiya, Thapar. All the Best"
    else
      @submit = "Congratulations! You hvae qualified for JEE Advanced.You will get any NIT you would apply for. All the Best"
    end
  end
def srm(m)
  m=m.to_i
  if m>=0 && m<=1000
   @submit = " Congratulations! You will get all branches in all campuses."
  elsif
    m>1000 && m<=2000
    @submit = "Congratulations! You will get any other branch than CS in main campus. You will get all branches in all other campuses"
  elsif
    m>1000 && m<4000
    @submit = " Congratulations! You will get any other branch than CS and Mechanical in main campus. You will get all branches in all other campuses"
  elsif
    m>4000 && m<=10000
    @submit = " Congratulations! You will get any other branch than CS, Mechanical,I.T in main campus. You will get all branches in all other campuses"

    elsif
    m>10000 && m<=30000
    @submit ="Congratulations! You will get all branches in all other campuses"
  elsif
    m>30000 && m<=55000
    @submit = "Congratulations! You will get some lower branches in SRM,Delhi"
  else
    @submit = "Sorry! no results found"

  end
end


end

app/controllers/eligibilty_controller.rb
class EligibiltyController < ApplicationController
layout('eligibilty')
  def new
  end
end
 

app/controllers/game_controller.rb
class GameController < ApplicationController
  layout 'application1'
  def create
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"


  def new
    @na=params[:theme]
    @nam=params[:themee]
    @name=params[:them]
    @other=params[:the]
    @lol=params[:th]
    @lmao=params[:demo]
    @die=params[:mod]
    @died=params[:modu]
    @tiger=params[:modue]
    @dino=params[:moduo]
    find( @na)
    found( @nam)
    like( @name)
    done(@other)
    hit(@lol)
    bat(@lmao)
    kit(@die)
    did(@died)
    tit(@tiger)
    kid(@dino)
  end
def find(answer)
  if answer == 'New-York'
    @submt = 1
    @subr= "your answer is right"
  else
    @subr= 'your answer is wrong'
    @submt = 0
  end
end
  def found(ans)
    if ans == '49'
      @submt+= 1
      @sub=  "your answer is right"
    else
      @sub= "your answer is wrong"

    end
end
  def like(an)
    if an == 'leaf'
      @submt+= 1
      @give=  "your answer is right"
    else
      @give= "your answer is wrong"

    end
  end
  def done(jawab)
    if jawab == 'boat'
      @submt+= 1
      @given=  "your answer is right"
    else
      @given= "your answer is wrong"

    end
  end

  def hit(hut)
    if hut == 'Monday'
      @submt+= 1
      @gave=  "your answer is right"
    else
      @gave= "your answer is wrong"

    end
  end
  def bat(bit)
    if bit == '132'
      @submt+= 1
      @steal=  "your answer is right"
    else
      @steal= "your answer is wrong"

    end
  end
  def kit(kat)
    if kat == 'Beef'
      @submt+= 1
      @stolen=  "your answer is right"
    else
      @stolen= "your answer is wrong"

    end
  end
  def did(dod)
    if dod == '14'
      @submt+= 1
      @rage=  "your answer is right"
    else
      @rage= "your answer is wrong"
    end
  end
  def tit(tat)
    if tat == '125 cubic metres'
      @submt+= 1
      @lion=  "your answer is right"
    else
      @lion= "your answer is wrong"
    end
  end
  def kid(kidd)
    if kidd == '60km/hr'
      @submt+= 1
      @deer=  "your answer is right"
    else
      @deer= "your answer is wrong"
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  layout 'index'
  def index
  end
end

app/controllers/iqtest_controller.rb
class IqtestController < ApplicationController
  layout 'iqtest'
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counselor_helper.rb
module CounselorHelper
end

app/helpers/creator_helper.rb
module CreatorHelper
end

app/helpers/el_helper.rb
module ElHelper
end

app/helpers/eligibilty_helper.rb
module EligibiltyHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/iqtest_helper.rb
module IqtestHelper
end

app/views/counselor/index.html.erb
<body background=" https://af-production.s3.amazonaws.com/photos/images/76458/original/books.jpg">
<div class="cow">
  <p> <b>Thanks for submitting your query</b> </p>
<p> Check your email after 10mins. </p>
<p> Hey! while you wait for reply, why don't you try this game <br> <%= link_to "Shoot the Birds",game_create_path%></li></p>
</div>
<a class="kill" href="/counselor/show"><b>Submit another query</b></a>
<a class="kill1"href="/index/index"><b>Home</b></a>
</body>

app/views/counselor/new.html.erb
<h1>Counselor#new</h1>
<p>Find me in app/views/counselor/new.html.erb</p>

app/views/counselor/show.html.erb
<body background=" https://af-production.s3.amazonaws.com/photos/images/76458/original/books.jpg">
<div class="tata">
<%=form_for @msg ,url: counselor_new_path do  |msg| %>
      <p><b> Please enter your name.</b> </p>
    <%= msg.text_field :name %>
    <p><b> Please enter your email id.</b> </p>
    <%= msg.text_field :email_id %>
    <p><b> Please enter your query.</b></p>
    <%= msg.text_area  :query %><br>

    <%= msg.submit "Submit"%>
<% end %>
</div>
<div class="merc">
  <a href="/index/index"><b>Home</b></a>
  <a href="/eligibilty/new"><b>Eligibility</b></a>
  </div>
</body>

app/views/creator/index.html.erb
<body class="ankan" background="https://previews.123rf.com/images/1stchoice/1stchoice1606/1stchoice160600042/58901945-Abstract-natural-light-brown-background-beige-earth-tone-soil-texture-Stock-Photo.jpg" >
<h>
<IMG class="ankit" src="https://scontent.fmaa1-1.fna.fbcdn.net/v/t1.0-9/15977990_10207784301997648_529873926269166464_n.jpg?oh=cb439cbe88cd46277868b45ca0f0d086&oe=59DF026D">
</h>
<div class="boxed">
<P class="riu">
  This webiste is created by Ankan Kumar.
  He is an engineer in the making.<br> This webiste is created as a summer project.
  It is created using ruby on rails.<br>
  Hope you liked it!<br>
  If any bugs are there, kindly mail on ankan.muj@gmail.com <br> <br>
  <b><div class="mega">About this website .</div></b> <br>
  <div class="rope"><b>Eligibility </b></div>
<P>The eligibility page helps you find the best college availaible from exams like IIT Mains, Manipal and SRMJEE
For Manipal and Mains kindly enter marks and for SRMJEE enter rank.</P>
    <b><div class="rope"> Counselor </div></b>
<p>  After knowing a college, the question that pops in a person's head is "Which one to go for?"</p>
    You can take help of our counselor for any inquery.<br> <br>
    <b><div class="rope"> IQ Test </div></b>
<p>  The IQ Test page has 10 questions and you get 10mins to solve them. Its an authentic way to know your I.Q
     A score of 6 is regarded average where as a score of 8 and beyond is regarded as genius.  </p>

</P>
</div>
  <a class="volley" href="/index/index">Home</a>
</body>

app/views/el/index.html.erb
<body class="dog">

  <h2 class="adjust">

    <%=  @mark %>

<br> <%= @name %> </br>
</h2>

<h3 class="cat">
 <%= @submit%>
 <div class="her">
   <a href="/index/index"> Home </a>
</div>
<div class="his">
  <a href="/eligibilty/new">Back</a>
</div>
</h3>
</body>

app/views/eligibilty/new.html.erb
<body class="croc">
<h1 class="Tiger">
                                                 Eligibility
</h1>
<h2 class="lion">
Please enter given details.
   <a class="home" href="http://localhost:3000">Home</a>
</h2>
<h3 class="deer"><%= form_tag("/el/index",controller: "el", method: "index") do %>
    <p> Name of exam(SRM/Manipal/Mains)</p>
    <%= text_field_tag :fname %>
    <p> Your Marks/Rank</p>
    <%= text_field_tag :lname %>
    <%= submit_tag "submit" %>
<% end %>
</h3>

</body>

app/views/game/create.html.erb
<div class="wrapper">
  <div class="timer">
    <span></span>
  </div>
  <div class="gameover">GAME OVER
    <a class="restart" href="/game/create"> restart</a>
    <a class="restart" href="/index/index">home</a>
  </div>
  <h1>Shoot The Birds </h1>
  <input class="input-circle input-circle1" type="radio" id="circle1" >
  <input class="input-circle input-circle2" type="radio" id="circle2" >
  <input class="input-circle input-circle3" type="radio" id="circle3" >
  <input class="input-circle input-circle4" type="radio" id="circle4" >
  <input class="input-circle input-circle5" type="radio" id="circle5" >
  <input class="input-circle input-circle6" type="radio" id="circle6" >

  <label for="circle1" class="pajaro pajaro1"><span></span></label>
  <label for="circle2" class="pajaro pajaro2"><span></span></label>
  <label for="circle3" class="pajaro pajaro3"><span></span></label>
  <label for="circle4" class="pajaro pajaro4"><span></span></label>
  <label for="circle5" class="pajaro pajaro5"><span></span></label>
  <label for="circle6" class="pajaro pajaro6"><span></span></label>
  <div class="sum">SCORE:</div>
  <footer><a href="https://www.facebook.com/ankan04?ref=bookmarks">The Game Done By Ankan Kumar</a></footer>

</div>

app/views/home/new.html.erb
<body class="cricket" background="https://af-production.s3.amazonaws.com/photos/images/76458/original/books.jpg"></body>
<div class="reva">
<p>
<br>
<%=@na%>
</br>
Q1.<%= @subr %>
</p>

<br>
<%=@nam%>
</br>
<p>
Q2.<%= @sub %>
</p>

<br> <%=@name%> </br>
<p> Q3.
  <%= @give %>
  </p>

<p>
  <br>
  <%=@other%>
  </br>
 Q4. <%= @given %>
</p>


  <br>
  <%=@lol%>
  <br>

  Q5. <%= @gave %>
</p>
<p>
</div>
  <div class="hate">
  <br>
  <%=@lmao%>
  </br>
 Q6. <%= @steal %>
</p>
<p>
  <br>
  <%=@die%>
  </br>
 Q7. <%= @stolen %>
</p>
<p>
  <br>
  <%=@died%>
  </br>
 Q8. <%= @rage %>
</p>
<p>
  <br>
  <%=@tiger%>
  </br>
 Q9. <%= @lion %>
</p>
<p>
  <br>
  <%=@dino%>
  </br>
Q10.  <%= @deer %>
</p>
</div>
</body>
<h1 class="football">
  You have scored <%= @submt%> marks.
</h1>
<div class="volley">
  <a href="/index/index"><b>Home</b></a>
</div>

app/views/index/index.html.erb
<body class="main">
<div id="wrapper">

  <!-- Header -->
  <header id="header">
    <div class="logo">
      <span class="icon fa-diamond"></span>
    </div>

    <div class="content">
      <div class="inner">
        <h1 class="Edu">EduHelp</h1>
        <p>A site for every student. </p>
      </div>
    </div>
    <nav>
      <ul>
        <li><a href="/iqtest/show">I.QTest</a></li>
        <li><a href="/eligibilty/new">Eligibility</a></li>
        <li><a href="/counselor/show">Counselor</a></li>
        <li><a href="/creator/index">Creators</a></li>
        <!--<li><a href="#elements">Elements</a></li>-->
      </ul>
      </nav>
  </header>
</div>

<IMG STYLE="position:fixed; TOP:40px; LEFT:695px; WIDTH:55px; HEIGHT:55px" SRC="https://image.flaticon.com/icons/png/512/43/43078.png">

</body>

app/views/iqtest/show.html.erb
<body class="test" background="http://www.tomtate.net/BOOK_WITH_TAN_BACKGROUND.jpg">
<br>
<h class="title"> <b>I.Q TEST </b>  </h> <br>
<br>
<label>QUESTION-1: From these 4 words, pick the odd one out :</label>
  <%= form_tag("/home/new",controller: "home", method: "new") %>
  <% [ 'Canberra', 'Vienna', 'Madrid', 'New-York' ].each do |theme| %>
      <br><%= radio_button_tag :theme, theme, @theme == theme %> </br>
      <%= theme.humanize %>
<% end %>
<br>
<br>
<br>
<div>
  <label>QUESTION-2: Which number complete the following series:      144 121 100 81 64 ?  </label>
  <%= form_tag("/home/new",controller: "home", method: "new") %>
  <% [ '16', '36', '49', '216' ].each do |themee| %>
      <br><%= radio_button_tag :themee, themee, @themee == themee %> </br>
      <%= themee.humanize %>
  <% end %>
</div>
<br>
<br>
<div>
    <label>QUESTION-3: Forest is to tree as tree is to ?</label>
  <%= form_tag("/home/new",controller: "home", method: "new") %>
  <% [ 'plant', 'leaf', 'branch', 'mangrove' ].each do |them| %>
      <br><%= radio_button_tag :them, them, @them == them %> </br>
      <%= them.humanize %>
      </div>
  <% end %>
  <div>
    <br>
    <br>
    <label>QUESTION-4: 6121135 is to flame as 21215120 is to ?</label>
    <%= form_tag("/home/new",controller: "home", method: "new") %>
    <% [ 'voice', 'bald', 'boat', 'castle' ].each do |the| %>
        <br><%= radio_button_tag :the, the, @the == the %> </br>
        <%= the.humanize %>
        </div>
    <% end %>
     <div>
    <br>
    <br>
       <label>QUESTION-5: The day after the day after tomorrow is four days before Monday. What day is it today?</label>
    <%= form_tag("/home/new",controller: "home", method: "new") %>
    <% [ 'Monday', 'Thursday', 'Friday', 'Tuesday' ].each do |th| %>
        <br><%= radio_button_tag :th, th, @th == th %> </br>
        <%= th.humanize %>
        </div>
    <% end %>

    <div>
    <br>
    <br>
      <label>QUESTION-6: At a conference, 12 members shook hands with each other before & after the meeting.<br>
       How many total number of hand shakes occurred?</label>

    <%= form_tag("/home/new",controller: "home", method: "new") %>
    <% [ '100', '132', '133', '123' ].each do |demo| %>
        <br><%= radio_button_tag :demo, demo, @demo == demo %> </br>
        <%= demo.humanize %>
         </b>
         </div>

     <% end %>




        <div>
          <br>
          <br>
          <label>QUESTION-7: “Pig is to pork” as “Cow is to _____”: </label>
          <%= form_tag("/home/new",controller: "home", method: "new") %>
          <% [ 'Lamb', 'Beef', 'Cattle', 'Stew' ].each do |mod| %>
              <br><%= radio_button_tag :mod, mod, @mod == mod %> </br>
              <%= mod.humanize %>
              </div>
          <% end %>

          <div>
            <br>
            <br>
            <label>QUESTION-8: The following series of numbers contains one number that does not fit the pattern set by the others.<br>
              What number does not fit?  3, 5, 7, 11, 14, 17</label>
            <%= form_tag("/home/new",controller: "home", method: "new") %>
            <% [ '3', '7', '11', '14' ].each do |modu| %>
                <br><%= radio_button_tag :modu, modu, @modu == modu %> </br>
                <%= modu.humanize %>
                </div>
            <% end %>

            <div>
              <br>
              <br>
              <label>QUESTION-9: If you have a cube which is 5m x 5m x 5m, what is the cubic metres this container would hold? </label>
              <%= form_tag("/home/new",controller: "home", method: "new") %>
              <% [ '125 cubic metres', '120 cubic metres', '25 cubic metres', '225 cm' ].each do |modue| %>
                  <br><%= radio_button_tag :modue, modue, @modue == modue %> </br>
                  <%= modue.humanize %>
                  </div>
              <% end %>

              <div>
                <br>
                <br>
                <label>QUESTION-10: If it takes 2 hours to drive to City A and the city is 120km away,<br>
                  what speed was the vehicle travelling at?</label>
                <%= form_tag("/home/new",controller: "home", method: "new") %>
                <% [ '60km/hr', '100km/hr', '80km/hr', '40km/hr' ].each do |moduo| %>
                    <br><%= radio_button_tag :moduo, moduo, @moduo == moduo %> </br>
                    <%= moduo.humanize %>
                    </div>
                <% end %>
                <br>
                <br>
                <%= submit_tag("See your answers") %>
                <a class= "back" href="http://localhost:3000">Back</a>
                </div>
                <div id="pie_to_be"></div>
                <style>
                  div#pie_to_be { width: 50px; height: 50px; position: fixed; top:10px; right:10px; margin: 15px; color:#444444; font-family:arial; font-size:32px; }
                </style>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
                <script>
                    var myseconds = 600;
                    var mycolor = 'rgba(255, 100, 0, 0.8)';
                    alert('You will have '+Math.floor(myseconds/60)+' minutes and '+myseconds%60+' seconds to finish. Remember if time passes your answers will not be accepted. You will be redirected to quiz page  Press “OK” to begin.'); $(function(){ $('div#pie_to_be').pietimer({ seconds: myseconds, color: mycolor }, function(){ $('#caspioform').submit(); });}); (function($){jQuery.fn.pietimer=function(options,callback){var settings={'seconds':10,'color':'rgba(255, 255, 255, 0.8)','height':this.height(),'width':this.width()};if(options){$.extend(settings,options);}this.html('<canvas id="pie_timer" width="'+settings.height+'" height="'+settings.height+'">'+settings.seconds+'</canvas>');var val=360;interval=setInterval(timer,40);function timer(){var canvas=document.getElementById('pie_timer');if(canvas.getContext){val-=(360/settings.seconds)/24;if(val<=0){clearInterval(interval);canvas.width=canvas.width;if(typeof callback=='function'){callback.call();}}else{canvas.width=canvas.width;var ctx=canvas.getContext('2d');var canvas_size=[canvas.width,canvas.height];var radius=Math.min(canvas_size[0],canvas_size[1])/2;var center=[canvas_size[0]/2,canvas_size[1]/2];ctx.beginPath();ctx.moveTo(center[0],center[1]);var start=(3*Math.PI)/2;ctx.arc(center[0],center[1],radius,start-val*(Math.PI/180),start,false);ctx.closePath();ctx.fillStyle=settings.color;ctx.fill();}}}return this;};})(jQuery); var isMSIE = /*@cc_on!@*/0; if(isMSIE){function ticker(){document.getElementById('pie_to_be').innerHTML=parseInt(document.getElementById('pie_to_be').innerHTML)-1;} setInterval("ticker()",1000);}
                    window.setTimeout(function() {
                        window.location.href = '/iqtest/show';
                    }, 601000);
                </script>


                </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUMMER_PROJECT</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUMMER_PROJECT</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'game' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/counselor.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUMMER_PROJECT</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'counselor' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/creator.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUMMER_PROJECT</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'creator' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/eligibilty.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUMMER_PROJECT</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'eligibilty' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/home.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUMMER_PROJECT</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'home' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>SUMMER_PROJECT</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'index.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body background="https://s.smore.com/fr/books.18ceefdb.jpg">
<%= yield %>
</body>
</html>

app/views/layouts/iqtest.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUMMER_PROJECT</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'iqtest' %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>